-- ORIGINAL TABLES

CREATE TABLE PEOPLE(
ID INTEGER PRIMARY KEY,
AGE INTEGER,
GENDER ENUM('M','F'),
CITY VARCHAR(50)
);
CREATE TABLE PREFERENCES(
ID INTEGER PRIMARY KEY,
FOOD_TYPE VARCHAR(50),
FOREIGN KEY (ID) REFERENCES PEOPLE(ID)
);
CREATE TABLE JOB(
ID INTEGER PRIMARY KEY,
JOB VARCHAR(50),
FOREIGN KEY (ID) REFERENCES PEOPLE(ID)
);

CREATE TABLE COMBINED(  
AGE INTEGER,
GENDER ENUM('M','F'),
CITY VARCHAR(50),
FOOD_TYPE VARCHAR(50),
JOB VARCHAR(50),
STATE VARCHAR(50),
AGE_GROUP VARCHAR(50)
);

CREATE TABLE MEN AS SELECT * FROM COMBINED WHERE GENDER='M'; -- CREATING SEPARATE TABLE FOR MEN
CREATE TABLE WOMEN AS SELECT * FROM COMBINED WHERE GENDER='F'; -- CREATING SEPARATE TABLE FOR WOMEN

-- SEEING THE NUMBER OF MEN AND WOMEN IN THE ENTIRE POPULATION
SELECT GENDER,COUNT(*) FROM COMBINED GROUP BY GENDER;

-- AGE GROUP WISE ANALYSIS OF ENTIRE POPULATION
SELECT AGE_GROUP, COUNT(*) FROM COMBINED GROUP BY AGE_GROUP ORDER BY COUNT(*) DESC;

-- AGE GROUP WISE ANALYSIS OF MEN AND WOMEN 
SELECT AGE_GROUP,GENDER,COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY AGE_GROUP,GENDER ORDER BY AGE_GROUP;

-- AGE GROUP WISE ANALYSIS OF MEN AND WOMEN IN EACH STATE 
SELECT STATE,AGE_GROUP,GENDER,COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY STATE,AGE_GROUP,GENDER ORDER BY STATE,AGE_GROUP;

-- AGE GROUP WISE ANALYSIS OF MEN AND WOMEN IN EACH PROFESSION 
SELECT JOB,AGE_GROUP,GENDER,COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY AGE_GROUP,JOB,GENDER ORDER BY JOB,AGE_GROUP;

-- AGE GROUP WISE ANALYSIS OF MEN AND WOMEN LIKING EACH FOOD TYPE 
SELECT FOOD_TYPE, AGE_GROUP,GENDER,COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY FOOD_TYPE,GENDER,AGE_GROUP ORDER BY FOOD_TYPE,AGE_GROUP;

-- NUMBER OF CITY AND STATES 
SELECT COUNT(DISTINCT(CITY)) AS NUM_CITIES, COUNT(DISTINCT(STATE)) AS NUM_STATES FROM COMBINED;

-- POPULATION OF MEN AND WOMEN IN EACH CITY 
SELECT CITY, GENDER, COUNT(*) AS POPULATION FROM COMBINED GROUP BY CITY,GENDER ORDER BY CITY;

-- POPULATION OF MEN AND WOMEN IN EACH STATE 
SELECT STATE, GENDER, COUNT(*) AS POPULATION FROM COMBINED GROUP BY STATE,GENDER ORDER BY STATE;

-- NUMBER OF CITIES IN EACH STATE 
SELECT STATE, COUNT(DISTINCT(CITY)) AS CITIES FROM COMBINED GROUP BY STATE ORDER BY STATE;

-- ANALYSING EACH STATE IN DETAIL 
-- HARYANA 
-- PROMINENT CITIES IN HARYANA 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Haryana';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Haryana';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF HARYANA
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Haryana' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN HARYANA
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Haryana' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN HARYANA 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Haryana' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF HARYANA 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Haryana' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN HARYANA 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Haryana' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN HARYANA 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Haryana' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- RAJASTHAN 
-- PROMINENT CITIES IN RAJASTHAN 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Rajasthan';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Rajasthan';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF RAJASTHAN
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Rajasthan' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN RAJASTHAN
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Rajasthan' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN RAJASTHAN 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Rajasthan' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF RAJASTHAN 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Rajasthan' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN RAJASTHAN 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Rajasthan' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN RAJASTHAN 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Rajasthan' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- PUNJAB 
-- PROMINENT CITIES IN PUNJAB 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Punjab';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Punjab';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF PUNJAB
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Punjab' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN PUNJAB
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Punjab' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN PUNJAB 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Punjab' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF PUNJAB 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Punjab' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN PUNJAB 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Punjab' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN PUNJAB 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Punjab' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- HIMACHAL PRADESH 
-- PROMINENT CITIES IN HIMACHAL PRADESH 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Himachal Pradesh';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Himachal Pradesh';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF HIMACHAL PRADESH
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Himachal Pradesh' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN HIMACHAL PRADESH
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Himachal Pradesh' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN HIMACHAL PRADESH 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Himachal Pradesh' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF HIMACHAL PRADESH 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Himachal Pradesh' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN HIMACHAL PRADESH 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Himachal Pradesh' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN HIMACHAL PRADESH 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Himachal Pradesh' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- JAMMU 
-- PROMINENT CITIES IN JAMMU 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Jammu';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Jammu';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF JAMMU
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Jammu' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN JAMMU
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Jammu' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN JAMMU 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Jammu' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF JAMMU 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Jammu' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN JAMMU 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Jammu' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN JAMMU 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Jammu' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- UTTARAKHAND 
-- PROMINENT CITIES IN UTTARAKHAND 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Uttarakhand';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Uttarakhand';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF UTTARAKHAND
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Uttarakhand' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN UTTARAKHAND
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Uttarakhand' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN UTTARAKHAND 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Uttarakhand' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF UTTARAKHAND 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Uttarakhand' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN UTTARAKHAND 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Uttarakhand' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN UTTARAKHAND 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Uttarakhand' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- UTTAR PRADESH 
-- PROMINENT CITIES IN UTTAR PRADESH 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Uttar Pradesh';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Uttar Pradesh';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF UTTAR PRADESH
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Uttar Pradesh' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN UTTAR PRADESH
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Uttar Pradesh' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN UTTAR PRADESH 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Uttar Pradesh' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF UTTAR PRADESH 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Uttar Pradesh' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN UTTAR PRADESH 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Uttar Pradesh' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN UTTAR PRADESH 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Uttar Pradesh' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- BIHAR 
-- PROMINENT CITIES IN BIHAR 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Bihar';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Bihar';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF BIHAR
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Bihar' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN BIHAR
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Bihar' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN BIHAR 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Bihar' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF BIHAR 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Bihar' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN BIHAR 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Bihar' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN BIHAR 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Bihar' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- UNION TERRITORY 
-- PROMINENT CITIES IN UNION TERRITORY 
SELECT DISTINCT(CITY) FROM COMBINED WHERE STATE='Union Territory';
SELECT COUNT(DISTINCT(CITY)) FROM COMBINED WHERE STATE='Union Territory';
-- FOOD TYPE PREFERRED BY THE GENERAL POPULATION OF UNION TERRITORY
SELECT FOOD_TYPE, COUNT(*) FROM COMBINED WHERE STATE='Union Territory' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY MEN IN UNION TERRITORY
SELECT FOOD_TYPE, COUNT(*) FROM MEN WHERE STATE='Union Territory' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- FOOD TYPE PREFERRED BY WOMEN IN UNION TERRITORY 
SELECT FOOD_TYPE, COUNT(*) FROM WOMEN WHERE STATE='Union Territory' GROUP BY FOOD_TYPE ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY THE GENERAL POPULTAION OF UNION TERRITORY 
SELECT JOB, COUNT(*) FROM COMBINED WHERE STATE='Union Territory' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY MEN IN UNION TERRITORY 
SELECT JOB, COUNT(*) FROM MEN WHERE STATE='Union Territory' GROUP BY JOB ORDER BY COUNT(*) DESC;
-- JOBS PURSUED BY WOMEN IN UNION TERRITORY 
SELECT JOB, COUNT(*) FROM WOMEN WHERE STATE='Union Territory' GROUP BY JOB ORDER BY COUNT(*) DESC;

-- JOBS PURSUED BY MEN AND WOMEN 
SELECT JOB,GENDER,COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY GENDER,JOB ORDER BY JOB;

-- FOOD TYPES LIKED BY MEN AND WOMEN OF EACH PROFESSION 
SELECT JOB, FOOD_TYPE,GENDER,COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY GENDER,FOOD_TYPE,JOB ORDER BY FOOD_TYPE,JOB;

-- JOBS PURSUED BY MEN AND WOMEN OF EACH AGE GROUP 
SELECT AGE_GROUP, JOB, GENDER, COUNT(*) AS NUM_PPL FROM COMBINED GROUP BY AGE_GROUP, JOB, GENDER ORDER BY AGE_GROUP, JOB;